version: "3.0"
name: time-tracker
services:
  db-postgres:
    image: postgres:12.1-alpine
#   restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./share:/var/share
    network_mode: host

  db-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      SA_PASSWORD: "P@ss5678"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - ./mssql-data:/var/opt/mssql
        - ./share:/var/share
    network_mode: host
